version: '3'

services:
    web:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/app/
        links:
            - php

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/app/

    db:
        build:
            context: .
            dockerfile: docker/db/Dockerfile
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        volumes:
            - mysql_db_data_container:/var/lib/mysql

volumes:
    mysql_db_data_container: