#
# EXAMPLES
#
#routing:
#    homepage:
#        path: /
#        class: Quetzal\User\Controllers\SimpleController
#        action: index
#        method: GET
#    blog:
#        path: /blog/art
#        class: Quetzal\User\Controllers\BlogController
#        action: index
#        method: GET
#    blog_article:
#        path: /blog
#        class: Quetzal\User\Controllers\BlogController
#        action: index
#        method: GET
#    blog_page:
#        path: /blog/{Number}
#        class: Quetzal\User\Controllers\BlogController
#        action: index
#        method: GET
#    blog_page_string:
#        path: /blog/{String}
#        class: Quetzal\User\Controllers\BlogController
#        action: index
#        method: GET
#    blog_page_test1:
#        path: /blog/blog/*/*
#        class: Quetzal\User\Controllers\BlogController
#        action: index
#        method: GET
#    admin:
#        path: /admin
#        class: Quetzal\User\Controllers\SimpleController
#        action: index
#        method: GET
#

routing:
    homepage:
        path: /
        class: Quetzal\User\Controllers\AuthController
        action: loginView
        method: GET
    login_view:
        path: /login
        class: Quetzal\User\Controllers\AuthController
        action: loginView
        method: GET
    login:
        path: /login
        class: Quetzal\User\Controllers\AuthController
        action: loginUser
        method: POST
    logout:
        path: /logout
        class: Quetzal\User\Controllers\AuthController
        action: logoutUser
        method: GET
    register:
        path: /register
        class: Quetzal\User\Controllers\AuthController
        action: registerUser
        method: POST
    main-page:
        path: /main
        class: Quetzal\User\Controllers\MainController
        action: index
        method: GET
        guard: auth
    main-page-pictures:
        path: /pictures/all
        class: Quetzal\User\Controllers\MainController
        action: pictures
        method: GET
        guard: auth
    main-page-like-add:
        path: /likes/add
        class: Quetzal\User\Controllers\LikesController
        action: store
        method: POST
        guard: auth
    contests:
        path: /contests
        class: Quetzal\User\Controllers\ContestController
        action: index
        method: GET
        guard: auth
    contests-show:
        path: /contests/{Number}
        class: Quetzal\User\Controllers\ContestController
        action: show
        method: GET
        guard: auth
    contest-pictures:
        path: /contests/pictures/{Number}
        class: Quetzal\User\Controllers\ContestController
        action: indexByContest
        method: GET
        guard: auth
    contests-add:
        path: /contests
        class: Quetzal\User\Controllers\ContestController
        action: store
        method: POST
        guard: auth
    pixel-editor:
        path: /pixel-editor
        class: Quetzal\User\Controllers\PixelEditorController
        action: index
        method: GET
        guard: auth
    pixel-editor-save:
        path: /pixel-editor/save
        class: Quetzal\User\Controllers\PixelEditorController
        action: save
        method: POST
        guard: auth
